" "Hybrid" line numbers
set nu rnu " number relativenumber

set showcmd "shows command line on bottom

"set cursorline "highlight current line
set cursorline
" Default Colors for CursorLine
highlight  CursorLine cterm=bold ctermbg=236 ctermfg=None

set wildmenu
set lazyredraw
set showmatch

set incsearch "search as characters are typed
set hlsearch "highlight matches

set tabstop=2
set softtabstop=2
set expandtab "tabs are spaces

syntax on
set nocompatible
set backspace=indent,eol,start "enable typical backspace

" Highlight unwanted whitespace
set listchars=tab:>·,trail:~
set list

" Set leader
let mapleader=","

" Hide search highlighting
nnoremap <leader><space> :nohlsearch<CR>

" Show/Hide line numbers
nnoremap <F12> :set invnu<CR>:set invrnu<CR>
