source "${SCRIPTS_DIR}/modules/brew.sh"
source "${SCRIPTS_DIR}/modules/git_statusbar.sh"
source "${SCRIPTS_DIR}/modules/scripts_edit.sh"
source "${SCRIPTS_DIR}/modules/weather.sh"
source "${SCRIPTS_DIR}/modules/tmux.sh"
