source "${__SCRIPTS_DIR}/modules/brew.sh"
source "${__SCRIPTS_DIR}/modules/git_statusbar.sh"
[ -z "$__DISABLE_FZF" ] && source "${__SCRIPTS_DIR}/modules/scripts_edit.sh"
source "${__SCRIPTS_DIR}/modules/weather.sh"
source "${__SCRIPTS_DIR}/modules/tmux/tmux.sh"
