export BOLD="%B"
export RESET="%F{reset_color}%b"

export FG_RED="%F{124}"
export FG_LIGHTRED="%F{196}"
export FG_GREEN="%F{28}"
export FG_LIGHTGREEN="%F{118}"
export FG_YELLOW="%F{228}"
export FG_LIGHTYELLOW="%F{190}"
export FG_BLUE="%F{27}"
export FG_LIGHTBLUE="%F{111}"
export FG_MAGENTA="%F{134}"
export FG_LIGHTMAGENTA="%F{207}"
export FG_GREY="%F{242}"
export FG_LIGHTGREY="%F{252}"
export FG_WHITE="%F{15}"
